### ISSUE TITLE
Memory leaks in VerifyHash

### ISSUE THREAD

**Issue by madorin** [renegadebbs/pascal_bcrypt#4]
Function [VerifyHash](https://github.com/renegadebbs/pascal_bcrypt/blob/master/BCrypt.pas#L738)  have some early Exits: [Line 756](https://github.com/renegadebbs/pascal_bcrypt/blob/master/BCrypt.pas#L756), [L761](https://github.com/renegadebbs/pascal_bcrypt/blob/master/BCrypt.pas#L761), so [RegExp.Free](https://github.com/renegadebbs/pascal_bcrypt/blob/master/BCrypt.pas#L777) will never get called in case of exits.

Probably best way is to use a small check function like ValidHash instead using regular expressions.

**Comment by sikofitt** [comment]
I completely agree.  This is on the top of the to do list. (issue #1)   Sadly work and some other projects have left me neglecting this for awhile.

**Comment by madorin** [comment]
If i'll have some time, probably in next days, may implement a small check function.
By the way, does it compile OK under XE10? is it unicode-aware?
Ill need soon due to an extension written in Delphi of a PHP project.

**Comment by sikofitt** [comment]
Commit fe19f3bc4900d24198148f82803f9d83e620f465 should fix this.  Sorry it took 4+ months.  I'm guessing you probably implemented something else since then.

Also, I don't have any Delphi products to check if it compiles under that.  I think all implementations of bcrypt, unicode strings need to be encoded before hand.  I could be wrong though.
